[package]
name = "mpv-remote"
version = "0.1.0"
edition = "2021"

[lib]
name = "mpv_remote"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
byteorder = "1.5.0"
mpv-client = "1.0.1"
sha1 = "0.10.6"
tokio = "1.44.0"
